#+TITLE: Emacs Configuration
#+AUTHOR: Sai Pandian
#+EMAIL: saipandian97@gmail.com
#+STARTUP: overview

* Setting up New Installation
Make a small change to this file, delete the change, and then save the file.
Emacs will compile the file and install all necessary packages.
You may need to change the locations of some paths and add your own api
credentials. 

* General Tweaks to Emacs
Some tweaks to the default look and behaviour of emacs
#+BEGIN_SRC emacs-lisp
(setq byte-compile-warnings '(cl-functions))
(cd "~")
(show-paren-mode)
(setq make-backup-files nil)
(setq auto-save-default nil)
(setq inhibit-splash-screen t)

;; disable emacs completion window
(setq completion-auto-help 'lazy)

;; disable some warnings when compiling init file
(setq warning-minimum-level :error)

;; allow y-or-n instead of yes-or-no
(defalias 'yes-or-no-p 'y-or-n-p)

;; always follow symbolic links
(setq vc-follow-symlinks t)

;; scroll properly, not stupid emacs way
(setq scroll-conservatively 101)
(setq mouse-wheel-scroll-amount '(1))
(setq mouse-wheel-progressive-speed nil)

;; disable tool bar and scroll bar and menu bar if not in mac
(tool-bar-mode -1)
(scroll-bar-mode -1)

;; show line number and highlight current line
(global-display-line-numbers-mode)
(add-hook 'prog-mode-hook (lambda () (display-fill-column-indicator-mode 1)))
;; (global-hl-line-mode t)

;; disable line number in terminals and turn on hs minor mode when programming
(add-hook 'prog-mode-hook (lambda () (hs-minor-mode 1)))
(add-hook 'prog-mode-hook (lambda () (diminish 'hs-minor-mode)))
(add-hook 'term-mode-hook (lambda () (display-line-numbers-mode -1)))
(add-hook 'vterm-mode-hook (lambda () (display-line-numbers-mode -1)))
(add-hook 'eshell-mode-hook (lambda () (display-line-numbers-mode -1)))
(add-hook 'help-mode-hook (lambda () (display-line-numbers-mode -1)))

;; turn off bell
(setq ring-bell-function 'ignore)

(defalias 'ff 'find-file)

;; enable emacs server
(server-mode 1)

;; turn off indicator for wrapping text
(setf (cdr (assq 'continuation fringe-indicator-alist))
      '(nil nil))

(setq-default message-log-max nil)
(kill-buffer "*Messages*")

;; make emacs open maximised
(toggle-frame-maximized)

;; set default wrap length
(setq-default fill-column 80)
#+END_SRC

* MacOS Specific
If you install with brew install emacs-plus, there is a chance that Alfred will
not find the symlink. In this case, make a folder in /Applications called
Emacs.app, then delete the folder. And then do the symlink, and this will let
Alfred see it. It's a bit of a hack but it works.

#+BEGIN_SRC emacs-lisp
(set-frame-font "Roboto Mono 14" nil t)

;; get pretty header bars in macOS
(add-to-list 'default-frame-alist '(ns-transparent-titlebar .t))
(add-to-list 'default-frame-alist '(ns-appearance . dark))
(setq ns-use-proxy-icon nil)
(setq frame-title-format nil)

;; open new files from finder in already opened frame
(setq ns-pop-up-frames nil)

;; only hide emacs when x button pressed
(defun handle-delete-frame-without-kill-emacs (event)
  "Handle delete-frame events from the X server."
  (interactive "e")
  (let ((frame (posn-window (event-start event)))
        (i 0)
        (tail (frame-list)))
    (while tail
      (and (frame-visible-p (car tail))
           (not (eq (car tail) frame))
           (setq i (1+ i)))
      (setq tail (cdr tail)))
    (if (> i 0)
        (delete-frame frame t)
      ;; Not (save-buffers-kill-emacs) but instead:
      (ns-do-hide-emacs))))
      ;; can change to (suspend-frame) on non mac systems
(when (eq system-type 'darwin)
  (advice-add 'handle-delete-frame :override
              #'handle-delete-frame-without-kill-emacs))
#+END_SRC

* Themes
A nice collection of themes
#+begin_src emacs-lisp
(use-package doom-themes
  :ensure t
  :defer t
  :init
  (load-theme 'doom-one t))
#+end_src

* Mode Line
I change the font colours in the modeline
#+BEGIN_SRC emacs-lisp
(set-face-attribute 'mode-line nil
                    :background "#353644"
                    :foreground "white"
                    :overline nil
                    :underline nil)
#+END_SRC

Doom modeline is much lighter but still looks quite pretty
#+begin_src emacs-lisp
(use-package doom-modeline
  :ensure t
  :defer t
  :init
  (setq doom-modeline-height 10)
  (setq doom-modeline-bar-width 1)
  (setq doom-modeline-icon nil)
  (setq doom-modeline-minor-modes t)
  (setq doom-modeline-perp-name t)
  (setq doom-modeline-lsp t)
  (setq doom-modeline-env-version nil)
  (doom-modeline-mode 1))
#+end_src

* Magit
Magit is a wonderful git frontend for emacs
#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t
  :defer t
  :init
  (add-hook 'magit-mode-hook (lambda ()
			       (diminish 'auto-revert-mode)))
  (global-set-key (kbd "C-x g") 'magit-status))
#+END_SRC

* Evil
I am an ex-vim user so I use evil for my editing

Evil-collection fixes evil mode in many places
#+BEGIN_SRC emacs-lisp
(use-package evil-collection
  :ensure t
  :defer t
  :init
  (setq evil-want-C-i-jump nil)
  (setq evil-want-keybinding nil)
  (evil-collection-init))
#+END_SRC

Evil mode
#+BEGIN_SRC emacs-lisp
(use-package evil
  :ensure t
  :defer t
  :init
  (setq evil-want-keybinding nil)
  (setq evil-insert-state-message nil)
  (setq evil-visual-state-message nil)
  (setq evil-mode-line-format '(before . mode-line-front-space))
  (setq evil-normal-state-tag "NORMAL")
  (setq evil-insert-state-tag "INSERT")
  (setq evil-visual-state-tag "VISUAL")
  (setq evil-operator-state-tag "OPERATOR")
  (setq evil-motion-state-tag "MOTION")
  (setq evil-emacs-state-tag "EMACS")
  (evil-mode 1))
#+END_SRC

Evil commentary is a port of vim's commentary
#+BEGIN_SRC emacs-lisp
(use-package evil-commentary
  :ensure t
  :defer t
  :init
  (evil-commentary-mode 1))
#+END_SRC

Useful port of vim surround
#+BEGIN_SRC emacs-lisp
(use-package evil-surround
  :ensure t
  :defer t
  :init
  (global-evil-surround-mode 1))
#+END_SRC

Provides evil mode bindings in magit
#+BEGIN_SRC emacs-lisp
(use-package evil-magit
  :ensure t
  :defer t
  :init
  (add-hook 'magit-mode-hook (lambda () (evil-magit-init))))
#+END_SRC

Evil numbers for incrementing and decrementing
#+begin_src emacs-lisp
(use-package evil-numbers
  :ensure t
  :defer t
  :init
  (define-key evil-normal-state-map (kbd "C-c C-=") 'evil-numbers/inc-at-pt)
  (define-key evil-normal-state-map (kbd "C-c C--") 'evil-numbers/dec-at-pt))
#+end_src

* Iedit
Iedit allows for multiple cursor-like functionality
#+BEGIN_SRC emacs-lisp
(use-package iedit
  :ensure t
  :defer t)
#+END_SRC

* Company
I use company for all my autocompletion needs
#+BEGIN_SRC emacs-lisp
(use-package company
  :ensure t
  :defer t
  :init
  (global-company-mode)
  (push ".fbd_latexmk" company-files-exclusions)
  (push ".aux" company-files-exclusions)
  (push ".log" company-files-exclusions)
  (push ".pdf" company-files-exclusions)
  (push ".bcf" company-files-exclusions)
  (push ".gz" company-files-exclusions)
  (push ".blg" company-files-exclusions)
  (push ".fls" company-files-exclusions)
  (delete 'company-dabbrev company-backends)
  ;; (company-tng-configure-default)
  (setq company-idle-delay 0)
  (setq company-minimum-prefix-length 1)
  (setq company-tooltip-align-annotations t)
  (setq company-tooltip-limit 15)
  (add-hook 'pdf-view-mode-hook (lambda () (company-mode -1)))
  (add-hook 'eshell-mode-hook (lambda () (company-mode -1)))
  (add-hook 'term-mode-hook (lambda () (company-mode -1)))
  (add-hook 'shell-mode-hook (lambda () (company-mode -1))))
#+END_SRC

* Projectile
I use projectile to manage projects
#+BEGIN_SRC emacs-lisp
(use-package projectile
  :ensure t
  :defer t
  :init
  (projectile-mode 1)
  (define-key projectile-mode-map (kbd "C-x p") 'projectile-command-map))
#+END_SRC

* Which Key
I use which key to show me possible keyboard shortcuts
#+BEGIN_SRC emacs-lisp
(use-package which-key
  :ensure t
  :defer t
  :init
  (setq which-key-idle-delay 0.3)
  (setq which-key-idle-secondary-delay 0.05)
  (which-key-mode))
#+END_SRC

* Exec Path From Shell
This simply gets the shell variable and path from default shell
#+BEGIN_SRC emacs-lisp
(use-package exec-path-from-shell
  :ensure t
  :defer t
  :init
  (setq exec-path-from-shell-check-startup-files nil)
  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize)))
#+END_SRC

* Vterm
I use vterm as my terminal because it is a lot better than ansi-term. You will
need to have some dependencies installed for this, which can be done in mac with: 
brew install cmake libtool libvterm
#+begin_src emacs-lisp
(use-package vterm
  :ensure t
  :defer t)
#+end_src

* Perspective Mode
I use this for managing workspaces inside Emacs. Might be redunant with tabs in
Emacs 27
#+begin_src emacs-lisp
(use-package perspective
  :ensure t
  :defer t
  :init
  (global-set-key (kbd "C-x b") 'persp-ivy-switch-buffer)
  (global-set-key (kbd "C-x C-b") 'persp-ivy-switch-buffer)
  (global-set-key (kbd "C-x C-i") 'persp-ibuffer)
  (global-set-key (kbd "C-x k") 'persp-kill-buffer*)
  (global-set-key (kbd "C-x C-k") 'persp-kill-buffer*)
  (global-set-key (kbd "C-x x h") 'persp-prev)
  (global-set-key (kbd "C-x x l") 'persp-next)
  (custom-set-faces '(persp-selected-face ((t (:foreground "#FD7CC5")))))
  (persp-mode 1))
#+end_src

* Ivy, Counsel & Swiper
Counsel and Ivy-mode for completion
#+begin_src emacs-lisp
(use-package smex
  :ensure t
  :defer t)

(use-package counsel
  :ensure t
  :defer t
  :init
  (global-set-key "\C-s" 'swiper)
  (setq counsel-fzf-cmd "rg --files --hidden --no-ignore --glob '!.git/*'")
  (counsel-mode 1))

(use-package ivy
  :ensure t
  :defer t
  :init
  ;; (custom-set-faces '(ivy-current-match ((t (:background "#FF0000")))))
  (setq ivy-initial-inputs-alist nil)
  (setq enable-recursive-minibuffers t)
  (setq ivy-height 15)
  (define-key ivy-minibuffer-map (kbd "C-j") #'ivy-next-line)
  (define-key ivy-minibuffer-map (kbd "C-k") #'ivy-previous-line)
  (define-key ivy-switch-buffer-map (kbd "C-j") #'ivy-next-line)
  (define-key ivy-switch-buffer-map (kbd "C-k") #'ivy-previous-line)
  (define-key ivy-minibuffer-map (kbd "<return>") #'ivy-alt-done)
  (global-set-key (kbd "M-p") 'counsel-yank-pop)
  (setq projectile-completion-system 'ivy)
  (ivy-mode 1))
#+end_src

* Dashboard
Dashboard is the starting page when opening emacs
#+BEGIN_SRC emacs-lisp
(use-package dashboard
  :ensure t
  :defer t
  :init
  (setq initial-buffer-choice (lambda () (switch-to-buffer "*dashboard*")))
  (setq dashboard-startup-banner 'logo)
  (setq dashboard-banner-logo-title "It is only with the heart that one can see rightly; what is essential is invisible to the eye.")
  (setq dashboard-footer-messages '("Sai Pandian"))
  (setq dashboard-set-init-info nil)
  (setq dashboard-items '((recents  . 15)
  			    (projects . 5)))
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-center-content t)
  (dashboard-setup-startup-hook)
  (add-hook 'dashboard-mode-hook (lambda() (display-line-numbers-mode -1))))
#+END_SRC

* Dired
Make dired work as expected
#+BEGIN_SRC emacs-lisp
(put 'dired-find-alternate-file 'disabled nil)
#+END_SRC

* CSV Mode
Viewing CSVs is often useful
#+BEGIN_SRC emacs-lisp
(use-package csv-mode
  :ensure t
  :defer t
  :init
  (setq csv-align-padding 3)
  (add-hook 'csv-mode-hook (lambda () (csv-header-line)
                                      (csv-align-mode)
                                      (display-line-numbers-mode -1)
                                      (linum-mode 1))))
#+END_SRC

* Org Mode
Install org from org repos instead of built-in and assign some colours and general settings
#+begin_src emacs-lisp
(use-package org
  :ensure t
  :defer t

  :init

  ;; some hooks
  (add-hook 'org-mode-hook 'auto-fill-mode)
  (add-hook 'org-mode-hook 'visual-line-mode)
  (add-hook 'org-babel-after-execute-hook 'org-display-inline-images)
  (add-to-list 'auto-mode-alist '("\\.org\\'" . org-mode))

  ;; agenda files, refile targets and drawer targets
  (setq org-agenda-files (directory-files-recursively "~/Dropbox/Org/" "\\.org$"))
  (setq org-refile-targets '((org-agenda-files :maxlevel . 1)))
  (setq org-log-into-drawer "LOGBOOK")

  ;; make custom function that refreshes org files
  (defun my/refresh-org-files ()
    (interactive)
    (setq org-agenda-files (directory-files-recursively "~/Dropbox/Org/" "\\.org$"))
    (setq org-refile-targets '((org-agenda-files :maxlevel . 1))))

  ;; some general settings
  (setq org-outline-path-complete-in-steps nil)
  (setq org-refile-use-outline-path 'file)
  (setq org-refile-allow-creating-parent-nodes 'confirm)
  (setq org-hide-leading-stars nil)
  (setq org-startup-indented t)
  (setq org-hide-emphasis-markers t)
  (setq org-confirm-babel-evaluate nil)
  (setq org-src-fontify-natively t)
  (setq org-edit-src-content-indentation 0)
  (setq org-src-tab-acts-natively t)
  (setq org-agenda-default-appointment-duration 30)
  (setq org-log-done 'time)
  (setq org-ellipsis " ⌄")

  ;; heading sizes
  (custom-set-faces
   '(org-level-1 ((t (:inherit outline-1 :height 1.2))))
   '(org-level-2 ((t (:inherit outline-2 :height 1.0))))
   '(org-level-3 ((t (:inherit outline-3 :height 1.0))))
   '(org-level-4 ((t (:inherit outline-4 :height 1.0))))
   '(org-level-5 ((t (:inherit outline-5 :height 1.0))))
   '(org-document-title ((t :height 1.5)))
   )

  ;; keybindings
  (global-set-key (kbd "C-c a") 'org-agenda)
  (global-set-key (kbd "C-c c") 'org-capture)
  (defun my/list-org-files ()
    (interactive)
    (projectile-find-file-in-directory "~/Dropbox/Org/"))
  (global-set-key (kbd "C-c f") 'my/list-org-files)


  :config
  (add-to-list 'org-modules 'org-tempo t)
  (add-to-list 'org-modules 'org-habit t)

  (setq org-agenda-prefix-format
      (quote
       ((agenda . "%-18c%?-13t% s")
        (timeline . "% s")
        (todo . "%-18:c ")
        (tags . "%-18c")
        (search . "%-18c"))))
  
  (setq org-todo-keywords
	'((sequence "TODO" "WAIT" "SOMEDAY" "|" "DONE" "CANCELLED"))))
#+end_src

This gets org mode working with python, jupyter and emacs-lisp
#+BEGIN_SRC emacs-lisp
(org-babel-do-load-languages 
 'org-babel-load-languages 
 '((emacs-lisp . t)
   (python     . t)
   (jupyter    . t)))
#+END_SRC

Tell Org mode to make pdfs from latex with particular process
#+begin_src emacs-lisp
;; (setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))
(setq org-latex-pdf-process
      '("pdflatex -interaction nonstopmode -output-directory %o %f"
	  "bibtex %b"
	  "pdflatex -interaction nonstopmode -output-directory %o %f"
	  "pdflatex -interaction nonstopmode -output-directory %o %f"))
#+end_src

Make citations work when pdfs are made and make margins smaller
#+begin_src emacs-lisp
;; (require 'dash)
(setq org-latex-default-packages-alist
      (-remove-item
       '("" "hyperref" nil)
       org-latex-default-packages-alist))
(add-to-list 'org-latex-default-packages-alist '("" "natbib" "") t)
(add-to-list 'org-latex-default-packages-alist
	     '("linktocpage,
              pdfstartview=FitH,
              colorlinks, 
              linkcolor=blue,
              anchorcolor=blue, 
              citecolor=blue,
              filecolor=blue,
              menucolor=blue,
              urlcolor=blue"
	       "hyperref" nil) t)
(setq org-latex-packages-alist '(("tmargin=1in, bmargin=1in, lmargin=1in, rmargin=1in" "geometry" nil)))
#+end_src

Allow export to beamer
#+BEGIN_SRC emacs-lisp
(use-package ox-beamer
  :config
  (eval-after-load "ox-latex"
      '(add-to-list 'org-latex-classes
                    `("beamer"
                      ,(concat "\\documentclass[presentation]{beamer}\n"
                             "[DEFAULT-PACKAGES]"
                             "[PACKAGES]"
                             "[EXTRA]\n")
                      ("\\section{%s}" . "\\section*{%s}")
                      ("\\subsection{%s}" . "\\subsection*{%s}")
                      ("\\subsubsection{%s}" . "\\subsubsection*{%s}")))))
#+END_SRC

* Org Ref
I use Org Ref to handle citations in Org mode
#+begin_src emacs-lisp
(use-package org-ref
  :ensure t
  :defer t
  :init
  (setq bibtex-autokey-year-length 4
	  bibtex-autokey-name-year-separator "-"
	  bibtex-autokey-year-title-separator "-"
	  bibtex-autokey-titleword-separator "-"
	  bibtex-autokey-titlewords 2
	  bibtex-autokey-titlewords-stretch 1
	  bibtex-autokey-titleword-length 5)

  (setq org-ref-label-use-font-lock nil)
  (add-hook 'org-mode-hook (lambda ()
			     (require 'org-ref)
			     (require 'org-ref-pdf)
			     (require 'org-ref-url-utils)))
  :config
  (org-ref-ivy-cite-completion)
  (define-key org-ref-ivy-cite-keymap (kbd "C-k") 'ivy-previous-line)
  (define-key org-mode-map (kbd "C-c [") 'org-ref-ivy-insert-ref-link))
#+end_src

* Org GCal
Allows synchronisation with Google Calendar. Replace the appropriate variables
with the client id and secret.
#+begin_src emacs-lisp
(use-package org-gcal
  :ensure t
  :defer t
  :init
  (setq
   org-gcal-client-id ;; put client id below
   org-gcal-client-secret ;; put client secret below
   org-gcal-file-alist
   '(("saipandian97@gmail.com" . "~/Dropbox/Org/GCal/Personal Calendar.org")
     ("1uguohmrhenl3g657n7mot9l0k@group.calendar.google.com" . "~/Dropbox/Org/GCal/Work Calendar.org"))))
#+end_src

* Org Superstar
This enables nice looking icons in org headings
#+BEGIN_SRC emacs-lisp
(use-package org-superstar
  :ensure t
  :defer t
  :init
  (setq org-superstar-configure-like-org-bullets t)
  (add-hook 'org-mode-hook 'org-superstar-mode))
#+END_SRC

* Org Capture Templates
Some capture templates that suit my workflow
#+begin_src emacs-lisp
(setq org-capture-templates
      '(
	("n" "Quick Note" entry (file "~/Dropbox/Org/Inbox.org")
	 "* %?" :empty-lines 0)
	("e" "Quick Event" entry (file "~/Dropbox/Org/Inbox.org")
	 "* %?\n%^T")
	("p" "Quick Task - Personal" entry (file "~/Dropbox/Org/Inbox.org")
	 "* TODO %?" :empty-lines 0)
	("w" "Quick Task - Work" entry (file "~/Dropbox/Org/Inbox.org")
       "* TODO %?\n%i%a" :empty-lines 0)
	("f" "Monthly Finance Review" entry (file+olp+datetree "~/Dropbox/Org/Personal/Finance.org" "Monthly Review Log")
	 "** Monthly Finance Review [0/4] \n- [ ] Check Expenditure and Balance in Yolt\n- [ ] Update [[file+sys:~/Google Drive/Budgets/budget_20_21.xlsx][Budget Spreadsheet]]\n- [ ] Move Extra Revolut into Vault\n- [ ] Transfer money into Revolut\n- [ ] Mark TODO as DONE" :empty-lines 0 :jump-to-captured t :kill-buffer t)
	))
#+end_src

* Org Agenda Customisation
For a nice looking custom agenda
#+begin_src emacs-lisp
(setq org-agenda-custom-commands
      '(("n" "Custom agenda view"
	 (
	  (agenda)
	  (todo "TODO")
	  (todo "WAIT")
	  (todo "SOMEDAY")
	  ))))

(add-hook 'org-agenda-mode-hook (lambda () (display-line-numbers-mode -1)))
#+end_src

Custom keyboard shortcuts in org-agenda
#+begin_src emacs-lisp
(eval-after-load 'org-agenda
 '(progn
    (evil-set-initial-state 'org-agenda-mode 'normal)
    (evil-define-key 'normal org-agenda-mode-map
      (kbd "<RET>") 'org-agenda-switch-to
      (kbd "\t") 'org-agenda-goto
      "q" 'org-agenda-quit
      "r" 'org-agenda-redo
      "S" 'org-save-all-org-buffers
      "gj" 'org-agenda-goto-date
      "gJ" 'org-agenda-clock-goto
      "gm" 'org-agenda-bulk-mark
      "go" 'org-agenda-open-link
      "s" 'org-agenda-schedule
      "+" 'org-agenda-priority-up
      "," 'org-agenda-priority
      "-" 'org-agenda-priority-down
      "y" 'org-agenda-todo-yesterday
      "n" 'org-agenda-add-note
      "t" 'org-agenda-todo
      ;; ":" 'org-agenda-set-tags
      ";" 'org-timer-set-timer
      "i" 'org-agenda-clock-in-avy
      "O" 'org-agenda-clock-out-avy
      "u" 'org-agenda-bulk-unmark
      "x" 'org-agenda-exit
      "j"  'org-agenda-next-line
      "k"  'org-agenda-previous-line
      "vt" 'org-agenda-toggle-time-grid
      "va" 'org-agenda-archives-mode
      "vw" 'org-agenda-week-view
      "vl" 'org-agenda-log-mode
      "vd" 'org-agenda-day-view
      "vc" 'org-agenda-show-clocking-issues
      "g/" 'org-agenda-filter-by-tag
      "o" 'delete-other-windows
      "gh" 'org-agenda-holiday
      "gv" 'org-agenda-view-mode-dispatch
      "f" 'org-agenda-later
      "b" 'org-agenda-earlier
      "c" 'counsel-org-capture
      "e" 'org-agenda-set-effort
      "{" 'org-agenda-manipulate-query-add-re
      "}" 'org-agenda-manipulate-query-subtract-re
      "A" 'org-agenda-toggle-archive-tag
      "." 'org-agenda-goto-today
      "0" 'evil-digit-argument-or-evil-beginning-of-line
      "<" 'org-agenda-filter-by-category
      ">" 'org-agenda-date-prompt
      "F" 'org-agenda-follow-mode
      "D" 'org-agenda-deadline
      "H" 'org-agenda-holidays
      "J" 'org-agenda-next-date-line
      "K" 'org-agenda-previous-date-line
      "L" 'org-agenda-recenter
      "P" 'org-agenda-show-priority
      "R" 'org-agenda-clockreport-mode
      "Z" 'org-agenda-sunrise-sunset
      "T" 'org-agenda-show-tags
      "X" 'org-agenda-clock-cancel
      "[" 'org-agenda-manipulate-query-add
      "g\\" 'org-agenda-filter-by-tag-refine
      "]" 'org-agenda-manipulate-query-subtract
      )))
#+end_src

* Autopair
I use autopair to automatically pair quotes and parentheses
#+BEGIN_SRC emacs-lisp
(use-package autopair
  :ensure t
  :defer t
  :init
  (autopair-global-mode 1)
  (add-hook 'org-mode-hook #'(lambda () (push ?< (getf autopair-dont-pair :never)))))
#+END_SRC

* Writeroom
This centres the window in the frame which is nice when writing prose
#+begin_src emacs-lisp
(use-package writeroom-mode
  :ensure t
  :defer t
  :init
  (setq writeroom-bottom-divider-width 0)
  (setq writeroom-fullscreen-effect nil)
  (setq writeroom-mode-line 1)
  (setq writeroom-restore-window-config 1)
  (setq writeroom-width 121)
  (add-hook 'writeroom-mode-hook (lambda () 
				   (display-line-numbers-mode -1)
				   (org-indent-mode -1)
				   (setq fill-column 120)
				   (doom-modeline-mode 1))))
#+end_src

* YASnippets
This package provides snippet insertion
#+begin_src emacs-lisp
(use-package yasnippet
  :ensure t
  :defer t
  :diminish yas-minor-mode
  :init
  (yas-global-mode 1))
#+end_src

A collection of useful snippets
#+begin_src emacs-lisp
(use-package yasnippet-snippets
  :ensure t
  :defer t)
#+end_src

* Flyspell 
On the go spell-checking in Emacs You will need to install aspell on your system
for this to work. On MacOS: brew install aspell
#+begin_src emacs-lisp 
(setq ispell-program-name "/usr/local/bin/aspell") 
(setq ispell-dictionary "british")
(add-hook 'latex-mode-hook 'flyspell-mode) 
(add-hook 'text-mode-hook 'flyspell-mode) 
#+end_src

* Flycheck
Use flycheck as the syntax checker, but only after saving the file.
#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :diminish flycheck-mode
  :defer t)
#+end_src

* LSP
Language servers handle most of my languages
#+begin_src emacs-lisp
(setq lsp-keymap-prefix "C-l")

(use-package lsp-mode
  :ensure t
  :defer t
  :diminish lsp-mode
  :hook ((lsp-mode . lsp-enable-which-key-integration))
  :commands lsp
  :init
  (setq lsp-prefer-flymake nil)
  (setq lsp-modeline-diagnostics-enable nil)
  (setq lsp-signature-auto-activate t)
  (setq lsp-signature-render-documentation nil)
  (setq lsp-modeline-code-actions-enable nil)
  :config
  (lsp-treemacs-sync-mode 1)
  (define-key lsp-mode-map (kbd "M-]") 'lsp-find-definition)
  (define-key lsp-mode-map (kbd "M-[") 'xref-pop-marker-stack))

(use-package company-lsp
  :ensure t
  :defer t)

(use-package lsp-ivy 
  :ensure t
  :defer t
  :commands lsp-ivy-workspace-symbol)
#+end_src

* Python
I use the pyright server for Python
#+begin_src emacs-lisp
(use-package lsp-pyright
  :defer t
  :ensure t
  :hook (python-mode . (lambda () (require 'lsp-pyright) (lsp)))
  :config
  (add-hook 'conda-postactivate-hook (lambda () (lsp-restart-workspace)))
  (add-hook 'conda-postdeactivate-hook (lambda () (lsp-restart-workspace))))
#+end_src

Conda handles switching virtual environments
#+BEGIN_SRC emacs-lisp
(use-package conda
  :ensure t
  :defer t
  :init
  (setq conda-anaconda-home (expand-file-name "~/miniconda3"))
  (setq conda-env-home-directory (expand-file-name "~/miniconda3"))
  :config
  (conda-env-initialize-interactive-shells)
  (conda-env-initialize-eshell))
#+END_SRC

Turn off annoying python start message
#+begin_src emacs-lisp
(setq python-indent-guess-indent-offset-verbose nil)
#+end_src

Get nice sphinx doc generation
#+begin_src emacs-lisp
(use-package sphinx-doc
  :ensure t
  :defer t
  :diminish sphinx-doc-mode
  :init
  (add-hook 'python-mode-hook (lambda () (require 'sphinx-doc) (sphinx-doc-mode t))))
#+end_src

* Jupyter
I use Emacs Jupyter for jupyter notebooks
#+BEGIN_SRC emacs-lisp
(use-package jupyter
  :ensure t
  :defer t
  :init
  (setq org-babel-default-header-args:jupyter-python '((:async . "yes")
                                                       (:session . "py")
                                                       (:kernel . "python3")))
  (define-key jupyter-org-interaction-mode-map (kbd "C-c h") nil)
  (defun my/get-jupyter-aliases ()
    (org-babel-jupyter-aliases-from-kernelspecs))
  :hook
  (conda-postactivate . my/get-jupyter-aliases))

(add-to-list 'org-structure-template-alist '("j" . "src jupyter-python"))
#+END_SRC

Allow export to jupyter notebooks. This is a local file, available at [[https://github.com/jkitchin/ox-ipynb][ox-ipynb]] 
This script will automatically download it.
#+BEGIN_SRC emacs-lisp
(shell-command "bash ~/.emacs.d/oxipynb_download.sh")
#+END_SRC

Set up export to Jupyter notebooks
#+begin_src emacs-lisp
(use-package ox-ipynb
  :after org)
#+end_src

* LaTeX
I use the TexLab language server, installed with: brew install texlab
#+begin_src emacs-lisp
(use-package lsp-latex
  :ensure t
  :defer t
  :init
  (with-eval-after-load "tex-mode"
    (require 'lsp-latex)
    (add-hook 'tex-mode-hook 'lsp)
    (add-hook 'latex-mode-hook 'lsp))
  (with-eval-after-load "bibtex"
    (add-hook 'bibtex-mode-hook 'lsp))

  (setq lsp-latex-lint-on-change t)
  (setq lsp-latex-lint-on-save t)

  ;; function to open pdf associated with tex file
  (defun my/open-pdf ()
    (interactive)
    (buffer-file-name (other-buffer))
    ;; (find-file (replace-regexp-in-string ".tex" ".pdf" buffer-file-name))
    (shell-command (concat "open " (replace-regexp-in-string " " "\\ " (replace-regexp-in-string ".tex" ".pdf" buffer-file-name) t t))))
  
  ;; function to save and build latex file
  (defun my/latex-build ()
    (interactive)
    (save-buffer)
    (lsp-latex-build))

  (add-hook 'latex-mode-hook (lambda () 
			       (define-key tex-mode-map (kbd "C-c C-c") 'my/latex-build)
			       (define-key tex-mode-map (kbd "C-c C-v") 'my/open-pdf))))
#+end_src

Some general latex settings
#+begin_src emacs-lisp
(add-hook 'latex-mode-hook 'auto-fill-mode)
(add-hook 'latex-mode-hook 'visual-line-mode)
(add-hook 'latex-mode-hook 'display-fill-column-indicator-mode)
#+end_src

* C/C++
I use the clangd server for C++. On Mac this is installed with:
brew install llvm
Make sure llvm is on your path.
#+begin_src emacs-lisp
(setq c-default-style "linux")
(add-hook 'c++-mode-hook (lambda () (lsp)))
#+end_src

* Java
I use the Eclipse JDT Language Server for Java development
#+begin_src emacs-lisp
(use-package lsp-java
  :ensure t
  :defer t
  :hook (java-mode . (lambda () (require 'lsp-java) (lsp)))
  :init
  (add-hook 'java-mode-hook (lambda () (diminish 'abbrev-mode))))
#+end_src

* General Key Bindings
Some general key bindings
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c t t") 'vterm)
(global-set-key (kbd "C-c t e") 'eshell)
(global-set-key (kbd "C-c t j") 'jupyter-run-repl)
(define-key key-translation-map (kbd "M-3") (kbd "#"))
(define-key key-translation-map (kbd "M-2") (kbd "€"))
(windmove-default-keybindings)

(global-set-key (kbd "C-c h") 'evil-window-left)
(global-set-key (kbd "C-c j") 'evil-window-down)
(global-set-key (kbd "C-c k") 'evil-window-up)
(global-set-key (kbd "C-c l") 'evil-window-right)
(global-set-key (kbd "C-c H") 'evil-window-move-far-left)
(global-set-key (kbd "C-c J") 'evil-window-move-very-bottom)
(global-set-key (kbd "C-c K") 'evil-window-move-very-top)
(global-set-key (kbd "C-c L") 'evil-window-move-far-right)
#+END_SRC

* Auto Update Packages
This package allows me to set autoupdate of packages
#+begin_src emacs-lisp
(use-package auto-package-update
  :ensure t
  :defer t
  :init
  (setq auto-package-update-delete-old-versions t
	auto-package-update-prompt-before-update t
	auto-package-update-interval 7)
  (auto-package-update-maybe))
#+end_src

* Diminished Modes
I diminish modes last since otherwise it doesn't seem to work
#+BEGIN_SRC emacs-lisp
(use-package diminish
  :ensure t
  :defer t
  :init
  (diminish 'page-break-lines-mode)
  (diminish 'counsel-mode)
  (diminish 'ivy-mode)
  (diminish 'yas-minor-mode)
  (diminish 'projectile-mode)
  (diminish 'undo-tree-mode)
  (diminish 'hs-minor-mode)
  (diminish 'evil-commentary-mode)
  (diminish 'eldoc-mode)
  (diminish 'auto-revert-mode)
  (diminish 'autopair-mode)
  (diminish 'which-key-mode)
  (diminish 'company-mode)
  (diminish 'highlight-indentation-mode)
  (diminish 'beacon-mode)
  (diminish 'persp-mode)
  (diminish 'smartparens-mode))
#+END_SRC

