#!/bin/bash

# customize these
WGET=/usr/bin/wget
ICS2ORG=~/dotfiles/scripts/personal_calendar_convert.awk
ICSFILE=~/tmp_personal.org
ORGFILE=~/Syncthing/Org/Personal_Calendar.org
URL=Changeme

# no customization needed below

$WGET -O $ICSFILE $URL
$ICS2ORG < $ICSFILE > $ORGFILE
rm -rf $ICSFILE
