#!/bin/bash

# customize these
WGET=/usr/bin/wget
ICS2ORG=~/dotfiles/scripts/sasia_calendar_convert.awk
ICSFILE=~/tmp_sasia.org
ORGFILE=~/Syncthing/Org/Sasia_Calendar.org
URL=Changeme

# no customization needed below

$WGET -O $ICSFILE $URL
$ICS2ORG < $ICSFILE > $ORGFILE
rm -rf $ICSFILE
