plugins: inline convert web embedart fetchart ftintitle lastgenre
fetchart:
    cautious: true
    sources: itunes *
ftintitle:
    auto: yes
    drop: no
convert:
    copy_album_art: yes
    embed: yes
    format: alac
